// App metadata
export const APP_NAME = "CloudiFlow-9000";
export const APP_DESCRIPTION =
  "Visual Infrastructure-as-Code generator. Design cloud architecture, generate Terraform, Pulumi & Ansible.";

// Storage keys
export const STORAGE_KEY = "cloudforge_state";
export const CANVAS_STORAGE_PREFIX = "cloudforge_canvas_";

// Default filenames for code export
export const DEFAULT_EXPORT_FILENAME = "cloudiflow-infra";

// Generator headers
export const GENERATOR_COMMENT_HASH = `# Generated by ${APP_NAME}`;
export const GENERATOR_COMMENT_SLASH = `// Generated by ${APP_NAME}`;

// Provider brand colors
export const PROVIDER_COLORS = {
  aws: "#ff9900",
  gcp: "#4285f4",
  azure: "#0078d4",
} as const;
