import type { CanvasNode, CanvasEdge } from "~/types";

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

function toSnakeCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function getNodeInputs(node: CanvasNode, edges: CanvasEdge[]): string[] {
  return edges
    .filter(edge => edge.target === node.id)
    .map(edge => {
      const sourceNode = edge.source;
      return `resource "aws_vpc" "${toSnakeCase(sourceNode)}"`;
    });
}

export function generateTerraform(nodes: CanvasNode[], edges: CanvasEdge[]): string {
  let code = `# Generated by CloudiFlow-9000
# Terraform Configuration

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS Region"
  type        = string
  default     = "us-east-1"
}

`;

  nodes.forEach((node) => {
    const { component, config } = node.data;
    const resourceName = toPascalCase(node.data.label);

    switch (component.id) {
      case "aws-ec2":
        code += `
resource "aws_instance" "${toSnakeCase(resourceName)}" {
  ami           = "${config.ami || "ami-0c55b159cbfafe1f0"}"
  instance_type = "${config.instanceType || "t2.micro"}"

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      case "aws-vpc":
        code += `
resource "aws_vpc" "${toSnakeCase(resourceName)}" {
  cidr_block           = "${config.cidrBlock || "10.0.0.0/16"}"
  enable_dns_hostnames = ${config.enableDnsHostnames ?? true}
  enable_dns_support   = true

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      case "aws-s3":
        code += `
resource "aws_s3_bucket" "${toSnakeCase(resourceName)}" {
  bucket = "${config.bucketName || "my-bucket"}"

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      case "aws-rds":
        code += `
resource "aws_db_instance" "${toSnakeCase(resourceName)}" {
  identifier           = "${toSnakeCase(resourceName)}"
  engine              = "${config.engine || "mysql"}"
  instance_class      = "${config.instanceClass || "db.t3.micro"}"
  allocated_storage   = ${config.allocatedStorage || 20}
  username            = "admin"
  password            = var.rds_password
  skip_final_snapshot = true
}

variable "rds_password" {
  description = "RDS Password"
  type        = string
  sensitive   = true
}
`;
        break;

      case "aws-lambda":
        code += `
resource "aws_lambda_function" "${toSnakeCase(resourceName)}" {
  function_name = "${resourceName}"
  runtime      = "${config.runtime || "nodejs20.x"}"
  timeout      = ${config.timeout || 30}
  memory_size   = ${config.memory || 128}

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      case "aws-elb":
        code += `
resource "aws_lb" "${toSnakeCase(resourceName)}" {
  name               = "${toSnakeCase(resourceName)}"
  internal           = ${config.scheme === "internal"}
  load_balancer_type = "${config.loadBalancerType || "application"}"

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      case "aws-sg":
        code += `
resource "aws_security_group" "${toSnakeCase(resourceName)}" {
  name        = "${resourceName}"
  description = "${config.description || "Security group"}"

  tags = {
    Name = "${resourceName}"
  }
}
`;
        break;

      default:
        code += `
# Resource: ${component.name}
# ${component.description}
# TODO: Add configuration for ${component.id}
`;
    }
  });

  return code;
}

export function generatePulumi(nodes: CanvasNode[], edges: CanvasEdge[]): string {
  let code = `// Generated by CloudForge
// Pulumi Configuration

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();
const region = config.get("awsRegion") || "us-east-1";

`;

  nodes.forEach((node) => {
    const { component, config } = node.data;
    const resourceName = toPascalCase(node.data.label);

    switch (component.id) {
      case "aws-ec2":
        code += `
const ${resourceName} = new aws.ec2.Instance("${resourceName}", {
  ami: "${config.ami || "ami-0c55b159cbfafe1f0"}",
  instanceType: "${config.instanceType || "t2.micro"}",
  tags: {
    Name: "${resourceName}",
  },
});
`;
        break;

      case "aws-vpc":
        code += `
const ${resourceName} = new aws.ec2.Vpc("${resourceName}", {
  cidrBlock: "${config.cidrBlock || "10.0.0.0/16"}",
  enableDnsHostnames: ${config.enableDnsHostnames ?? true},
  enableDnsSupport: true,
  tags: {
    Name: "${resourceName}",
  },
});
`;
        break;

      case "aws-s3":
        code += `
const ${resourceName} = new aws.s3.Bucket("${resourceName}", {
  bucket: "${config.bucketName || "my-bucket"}",
  tags: {
    Name: "${resourceName}",
  },
});
`;
        break;

      default:
        code += `
// Resource: ${component.name}
const ${resourceName} = null; // TODO: Add configuration for ${component.id}
`;
    }
  });

  return code;
}

export function generateAnsible(nodes: CanvasNode[], edges: CanvasEdge[]): string {
  let code = `# Generated by CloudiFlow-9000
# Ansible Playbook

- name: Deploy Cloud Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-east-1

  tasks:
`;

  nodes.forEach((node) => {
    const { component, config } = node.data;

    switch (component.id) {
      case "aws-ec2":
        code += `
    - name: Create EC2 instance - ${node.data.label}
      community.aws.ec2_instance:
        name: ${node.data.label}
        instance_type: ${config.instanceType || "t2.micro"}
        image_id: ${config.ami || "ami-0c55b159cbfafe1f0"}
        region: "{{ region }}"
        state: present
`;
        break;

      case "aws-vpc":
        code += `
    - name: Create VPC - ${node.data.label}
      community.aws.ec2_vpc_net:
        name: ${node.data.label}
        cidr_block: ${config.cidrBlock || "10.0.0.0/16"}
        region: "{{ region }}"
        state: present
`;
        break;

      default:
        code += `
    # TODO: Add task for ${component.name}
`;
    }
  });

  return code;
}

export function generateCode(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  format: "terraform" | "pulumi" | "ansible"
): string {
  switch (format) {
    case "terraform":
      return generateTerraform(nodes, edges);
    case "pulumi":
      return generatePulumi(nodes, edges);
    case "ansible":
      return generateAnsible(nodes, edges);
    default:
      return generateTerraform(nodes, edges);
  }
}
